language: ruby
cache: bundler
rvm: 2.4

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document

script:
  - bundle install
  - bundle exec jekyll build

env:
  matrix:
    - JEKYLL_VERSION="~> 4.0"
