title: 给忙碌者的育儿攻略
author:
  name: pythias
  email: pythias@gmail.com
description: >- 
  个人观点，仅供参考。与其说是攻略，倒不如说是我家孩子生活中的点滴更贴切一些
baseurl: ""
url: "https://c.jie.sh/"
updated_at: 2020-03-10 16:45

minima:
  social_links:
    github: pythias
    weibo: 1763952531
    weibo_username: 陈杰要骑车

disqus:
  shortname: new-parents

header_pages:
 - topic.md
 - sport.md
 - education.md
 - gallery.md
 - about.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  topics:
    output: true
    permalink: /topic/:name
  shoppings:
    output: true
    permalink: /shopping/:name
  educations:
    output: true
    permalink: /education/:name
  sports:
    output: true
    permalink: /sport/:name
  references:
    output: true
    permalink: /reference/:name

exclude:
  - bin
  - README.md