title: 给忙碌者的育儿攻略
author:
  name: pythias
  email: pythias@gmail.com
description: >- 
  个人观点，仅供参考。与其说是攻略，倒不如说是我家孩子生活中的点滴更贴切一些
baseurl: ""
url: "https://c.jie.sh"
updated_at: 2020-03-10 16:45
google_analytics: G-VKB8V54Q4T
baidu_analytics: 8aad084bec1278763ad2c403badf54e5

minima:
  social_links:
    github: pythias
    weibo: 1763952531
    weibo_username: 陈杰要骑车

disqus:
  shortname: new-parents

livere:
  uid: MTAyMC80OTQ2MC8yNTk1Mg==

header_pages:
 - topic.md
 - sport.md
 - education.md
 - gallery.md
 - about.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  topics:
    output: true
    permalink: /topic/:name.html
  shoppings:
    output: true
    permalink: /shopping/:name.html
  educations:
    output: true
    permalink: /education/:name.html
  sports:
    output: true
    permalink: /sport/:name.html
  references:
    output: true
    permalink: /reference/:name.html
  paintings:
    output: true
    permalink: /paintings/:year/:month/:day/:name.html

exclude:
  - bin
  - README.md